In [8]:
import numpy as np
def Mat(R,C):

 matrix = []
 print("Enter the entries rowwise:")
 for i in range(R):          
     a =[]
     for j in range(C):      
          a.append(int(input()))
     matrix.append(a)
 return matrix
print("First matrix:")
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
a=Mat(R,C)
for i in range(R):
    for j in range(C):
        print(a[i][j], end = " ")
    print()
print("Second matrix:")
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
b=Mat(R,C)
for i in range(R):
    for j in range(C):
        print(b[i][j], end = " ")
    print()
#Dot product
c = np.matrix(a)
d = np.matrix(b)
print("\nDOT PRODUCT")
print("Dot product of two matrix:")
print(np.dot(c, d))
#Transpose
print("\nTRANSPOSE")
print("Transpose of first matrix:")
print(np.transpose(a))
print("Transpose of second matrix:")
print(np.transpose(b))
#Trace
print("\nTRACE OF MATRIX")
print("Trace of first matrix:")
print(np.trace(a))
print("Trace of second matrix:")
print(np.trace(b))
#Rank
print("\nRANK OF MATRIX")
print("Rank of first matrix is ",np.linalg.matrix_rank(a))
print("Rank of second matrix is ",np.linalg.matrix_rank(b))
#Determinant
print("\nDETERMINANT")
print("Determinant of first matrix is ",int(np.linalg.det(a)))
print("Determinant of second matrix is ",int(np.linalg.det(b)))
#Inverse
print("\nINVERSE OF MATRIX")
print("Inverse of first matrix is \n",np.linalg.inv(a))
print("Inverse of second matrix is \n",np.linalg.inv(b))
#Eigen value and Eigen Vector
print("\nEIGEN VALUE AND EIGEN VECTOR")
eigA,eigvtrA=np.linalg.eig(a)
eigB,eigvtrB=np.linalg.eig(b)
print("Eigen value and Eigen vector of first matrix is ",eigA," and \n",eigvtrA)
print("Eigen value and Eigen vector of second matrix is ",eigB," and \n",eigvtrB)


First matrix:
Enter the number of rows:2
Enter the number of columns:2
Enter the entries rowwise:
7
4
5
6
7 4 
5 6 
Second matrix:
Enter the number of rows:2
Enter the number of columns:2
Enter the entries rowwise:
9
8
6
1
9 8 
6 1 

DOT PRODUCT
Dot product of two matrix:
[[87 60]
 [81 46]]

TRANSPOSE
Transpose of first matrix:
[[7 5]
 [4 6]]
Transpose of second matrix:
[[9 6]
 [8 1]]

TRACE OF MATRIX
Trace of first matrix:
13
Trace of second matrix:
10

RANK OF MATRIX
Rank of first matrix is  2
Rank of second matrix is  2

DETERMINANT
Determinant of first matrix is  22
Determinant of second matrix is  -38

INVERSE OF MATRIX
Inverse of first matrix is 
 [[ 0.27272727 -0.18181818]
 [-0.22727273  0.31818182]]
Inverse of second matrix is 
 [[-0.02564103  0.20512821]
 [ 0.15384615 -0.23076923]]

EIGEN VALUE AND EIGEN VECTOR
Eigen value and Eigen vector of first matrix is  [11.  2.]  and 
 [[ 0.70710678 -0.62469505]
 [ 0.70710678  0.78086881]]
Eigen value and Eigen vector of second matrix i