In [1]:
"""Write a NumPy program to create an element-wise comparison(greater,greater equal,less,less equal)
of two given arrays"""
import numpy as np
x=np.array([3,6])
y=np.array([7,2])
print("The Arrays are:")
print(x)
print(y)
print("The Comparison are")
print("Greater:")
print(np.greater(x,y))
print("Greater equal:")
print(np.greater_equal(x,y))
print("Less:")
print(np.less(x,y))
print("Less equal:")
print(np.less_equal(x,y))

The Arrays are:
[3 6]
[7 2]
The Comparison are
Greater:
[False  True]
Greater equal:
[False  True]
Less:
[ True False]
Less equal:
[ True False]


In [2]:
"""Write a numpy program to create an array of even numbers from 30 to 70."""
import numpy as np
evn_arr=np.arange(30,71,2)
print("The array of even numbers from 30 to 70 are:")
print(evn_arr)

The array of even numbers from 30 to 70 are:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [3]:
"""Write a NumPy program to create a 3x3 identity matrix"""
import numpy as np
matrix=np.identity(3)
print('3x3 Identity matrix is:')
print(matrix)

3x3 Identity matrix is:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
"""Write a NumPy program to create a vector with values from 0 to 20 and change the sign of
the numbers in the range from 9 to 15."""
import numpy as np
x = np.arange(21)
print("Original vector is:")
print(x)
print("Vector after changing the sign of the numbers in the range from 9 to 15:")
x[(x >= 9) & (x <= 15)] *= -1
print(x)

Original vector is:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Vector after changing the sign of the numbers in the range from 9 to 15:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [5]:
"""Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal
equal to 1, 2, 3, 4, 5."""
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [6]:
"""Write a NumPy program to compute sum of all elements, sum of each column and sum of
each row of a given array."""
import numpy as np
x = np.array([[2,1],[5,3]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))


Original array:
[[2 1]
 [5 3]]
Sum of all elements:
11
Sum of each column:
[7 4]
Sum of each row:
[3 8]


In [8]:
"""Write a NumPy program to save a given array to a text file and load it."""
import numpy as np
import os
x = np.arange(9).reshape(3, 3)
print("Original array:")
print(x)
header = 'col1 col2 col3'
np.savetxt('sample.txt', x, fmt="%d", header=header) 
print("The text file is:")
txt = np.loadtxt('sample.txt')
print(txt)


Original array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
The text file is:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [12]:
"""Write a NumPy program to check whether two arrays are equal (element wise) or not."""
import numpy as np
arr1 = np.array([5, 1, 10])
arr2 = np.array([20, 1, 2])
print("Original arrays:")
print(arr1)
print(arr2)
print("\nResult after checking:")
print(arr1 == arr2)



Original arrays:
[ 5  1 10]
[20  1  2]

Result is
[False  True False]


In [15]:
"""Write a NumPy program to create a 4x4 array with random values, now create a new array
from the said array swapping first and last rows"""
import numpy as np 
arr = np.arange(16).reshape(-1, 4)
print("Original array:")
print(arr)
print("\nResultant array after swapping:")
arr1 = arr[::-1]
print(arr1)


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Resultant array after swapping:
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [16]:
"""Write a NumPy program to multiply two given arrays of same size element-by-element"""
import numpy as np 
arr1 = np.array([[2, 6, 5],
              [1, 3, 4]])
arr2 = np.array([[6, 2, 2],
              [9, 4, 5]])
print("First Array:") 
print(arr1)
print("Second Array:") 
print(arr2)
print("\nResultant array after multiplication:")
print(np.multiply(arr1, arr2))


First Array:
[[2 6 5]
 [1 3 4]]
Second Array:
[[6 2 2]
 [9 4 5]]

Resultant array after multiplication:
[[12 12 10]
 [ 9 12 20]]
